const TYPES = {
  coffee: {
    label: "Coffee",
    unit: "mg",
    defaultAmount: 135,
    amountKind: "number",
    quickLabel: "Coffee (12oz)",
    quickMeta: "135 mg",
  },
  energy_drink: {
    label: "Energy Drink",
    unit: "mg",
    defaultAmount: "celsius",
    amountKind: "variant",
    options: [
      { value: "red_bull", label: "Red Bull", mg: 80 },
      { value: "celsius", label: "Celsius", mg: 200 },
      { value: "monster", label: "Monster Energy", mg: 160 },
      { value: "alani_nu", label: "Alani Nu", mg: 200 },
      { value: "rockstar", label: "Rockstar Energy", mg: 160 },
      { value: "bang", label: "Bang Energy", mg: 300 },
      { value: "reign", label: "Reign Total Body Fuel", mg: 300 },
      { value: "ghost", label: "Ghost Energy", mg: 200 },
      { value: "nos", label: "NOS", mg: 160 },
      { value: "bloom", label: "Bloom Nutrition", mg: 150 },
    ],
    quickLabel: "Energy Drink",
    quickMeta: "Varies",
  },
  soda: {
    label: "Soda",
    unit: "mg",
    defaultAmount: "regular",
    amountKind: "variant",
    options: [
      { value: "diet", label: "Diet Coke", mg: 46 },
      { value: "regular", label: "Coca-Cola", mg: 34 },
      { value: "zero", label: "Coke Zero Sugar", mg: 34 },
    ],
    quickLabel: "Soda",
    quickMeta: "Varies",
  },
  marijuana: {
    label: "Marijuana",
    unit: "mg",
    defaultAmount: 10,
    amountKind: "number",
    quickLabel: "Marijuana",
    quickMeta: "10 mg",
  },
  // stimulant: {
  //   label: "Adderall / Vyvanse",
  //   unit: "dose",
  //   defaultAmount: "medium",
  //   amountKind: "intensity",
  //   quickLabel: "Adderall",
  //   quickMeta: "medium dose",
  // },
  alcohol: {
    label: "Alcohol",
    unit: "drinks",
    defaultAmount: 1,
    amountKind: "number",
    quickLabel: "Alcohol",
    quickMeta: "1 drink",
  },
  nap: {
    label: "Nap",
    unit: "min",
    defaultAmount: 30,
    amountKind: "number",
    quickLabel: "Nap",
    quickMeta: "30 min",
  },
  // nicotine: {
  //   label: "Nicotine",
  //   unit: "mg",
  //   defaultAmount: 6,
  //   amountKind: "number",
  //   quickLabel: "Nicotine",
  //   quickMeta: "6 mg",
  // },
  // caffeine: {
  //   label: "Caffeine",
  //   unit: "mg",
  //   defaultAmount: 100,
  //   amountKind: "number",
  //   quickLabel: "Caffeine",
  //   quickMeta: "100 mg",
  // },
  // workout: {
  //   label: "Workout",
  //   unit: "intensity",
  //   defaultAmount: "medium",
  //   amountKind: "intensity",
  //   quickLabel: "Workout",
  //   quickMeta: "medium",
  // },
  // meal: {
  //   label: "Meal",
  //   unit: "size",
  //   defaultAmount: "medium",
  //   amountKind: "size",
  //   quickLabel: "Meal",
  //   quickMeta: "medium",
  // },
  // stress: {
  //   label: "Stressor",
  //   unit: "level",
  //   defaultAmount: "medium",
  //   amountKind: "intensity",
  //   quickLabel: "Stress",
  //   quickMeta: "medium",
  // },
  // brightlight: {
  //   label: "Bright light",
  //   unit: "min",
  //   defaultAmount: 30,
  //   amountKind: "number",
  //   quickLabel: "Bright light",
  //   quickMeta: "30 min",
  // },
  // screen: {
  //   label: "Screen time",
  //   unit: "min",
  //   defaultAmount: 60,
  //   amountKind: "number",
  //   quickLabel: "Screen",
  //   quickMeta: "60 min",
  // },
};

const INTENSITY_OPTS = ["low", "medium", "high"];
const SIZE_OPTS = ["light", "medium", "heavy"];
