import XCTest
@testable import Drift

// Cross-language parity: DecayParityCases.json is generated by running the
// REAL js/decay.js engine (tests/generate_decay_parity_fixture.js) — this
// isn't a hand-copied snapshot, it's the actual JS output, so a failure here
// means the Swift port has drifted from the web app's math, not that a
// fixture is stale in some other way. Re-run the generator after any
// legitimate change to js/decay.js.
final class DecayEngineParityTests: XCTestCase {
    private struct ParityCase: Decodable {
        struct EventFixture: Decodable {
            let type: String
            let amount: String
            let atHour: Double
        }
        let name: String
        let events: [EventFixture]
        let scoreAtHour: Double
        let expectedScore: Double
        let expectedByType: [String: Double]
        let expectedTotalPenalty: Double
    }

    private static let epsilon = 1e-6

    private func loadCases() throws -> [ParityCase] {
        let bundle = Bundle(for: Self.self)
        guard let url = bundle.url(forResource: "DecayParityCases", withExtension: "json") else {
            XCTFail("DecayParityCases.json not found in test bundle — check project.yml resources")
            return []
        }
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode([ParityCase].self, from: data)
    }

    func testAllFixtureCasesMatchTheJSEngine() throws {
        let cases = try loadCases()
        XCTAssertFalse(cases.isEmpty, "expected at least one parity case")

        let baseDate = ISO8601DateFormatter.drift.date(from: "2026-01-01T00:00:00Z")!

        for testCase in cases {
            let events = testCase.events.compactMap { fixture -> LogEvent? in
                guard let type = EventType(rawValue: fixture.type) else {
                    XCTFail("\(testCase.name): unknown event type \(fixture.type)")
                    return nil
                }
                let time = baseDate.addingTimeInterval(fixture.atHour * 3600)
                return LogEvent(id: UUID().uuidString, type: type, amount: fixture.amount, time: time)
            }
            let scoreAt = baseDate.addingTimeInterval(testCase.scoreAtHour * 3600)

            let result = Scoring.score(events: events, at: scoreAt)

            XCTAssertEqual(
                result.score, testCase.expectedScore, accuracy: Self.epsilon,
                "\(testCase.name): score mismatch"
            )
            XCTAssertEqual(
                result.totalPenalty, testCase.expectedTotalPenalty, accuracy: Self.epsilon,
                "\(testCase.name): totalPenalty mismatch"
            )

            let expectedByType = Dictionary(uniqueKeysWithValues: testCase.expectedByType.compactMap { key, value -> (EventType, Double)? in
                guard let type = EventType(rawValue: key) else { return nil }
                return (type, value)
            })
            XCTAssertEqual(
                result.byType.keys.sorted(by: { $0.rawValue < $1.rawValue }),
                expectedByType.keys.sorted(by: { $0.rawValue < $1.rawValue }),
                "\(testCase.name): byType keys mismatch"
            )
            for (type, expectedValue) in expectedByType {
                XCTAssertEqual(
                    result.byType[type] ?? -1, expectedValue, accuracy: Self.epsilon,
                    "\(testCase.name): byType[\(type.rawValue)] mismatch"
                )
            }
        }
    }
}
